---
title: "Rick Rubin Pre-Test"
author: "Diana Ginzburg, Joana Langhauser, Paula Mader, Nora Greß"
date: "Wintersemester 25/26"
output: html_document
---

# Setup und Lernziele

**Quellen:** [GitHub](https://github.com/Joana169/Rick-Rubin-network) 
[Codebuch](https://github.com/Joana169/Rick-Rubin-network/blob/main/codebuch.md)

## Laden der Programmbibliotheken

# Netzwerk einlesen

```{r setup und Netzwerk einlesen}

library(igraph)

el <- read.csv(
  "https://raw.githubusercontent.com/Joana169/Rick-Rubin-network/refs/heads/main/Edgelist_RickRubin_pretest%20(2).csv",
  header = TRUE, sep = ",", stringsAsFactors = FALSE
)

nl <- read.csv(
  "https://raw.githubusercontent.com/Joana169/Rick-Rubin-network/refs/heads/main/Nodelist_RickRubin_pretest.csv",
  header = TRUE, sep = ",", stringsAsFactors = FALSE
)

aw <- graph_from_data_frame(
  d = el,
  vertices = nl,
  directed = TRUE
)

aw

```

# Visualisierung 

```{r Visualisierung Anne Will, fig.height=9, fig.width=12}

# Visualisierung
plot(aw, # ruft das Netzwerk auf
     asp=0,# nutzt die komplette Leinwand des Chunks
     main="Gäste bei Anne Will Folgen 500-503")
```


